name: Export Yolo v5 Annotations

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  export:
    name: "Export Yolo v5 annotations"
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Setup ssh authorization
        env:
          SSH_PRIVATE_KEY: ${{secrets.RSA_PRIVATE_KEY}}
          SSH_PUBLIC_KEY: ${{secrets.RSA_PUBLIC_KEY}}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PUBLIC_KEY" | tr -d '\r' > ~/.ssh/id_rsa.pub
          chmod 700 ~/.ssh/id_rsa.pub
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          echo SSH agent started
          ssh-add -v ~/.ssh/id_rsa
          ssh-keyscan -H 'github.com' >> ~/.ssh/known_hosts
          ssh-keyscan ${{secrets.HOST}} >> ~/.ssh/known_hosts
      - name: Update pipelines
        run: ssh -p ${{secrets.SSH_PORT}} ${{secrets.USERNAME}}@${{secrets.HOST}} 'cd rocc-pipelines && git pull'
      - name: Prepare export script
        run: ssh -p ${{secrets.SSH_PORT}} ${{secrets.USERNAME}}@${{secrets.HOST}} 'cd rocc-pipelines && chmod u+x ./export-yolov5-annotations.sh'
      - name: Run export
        run: ssh -p ${{secrets.SSH_PORT}} ${{secrets.USERNAME}}@${{secrets.HOST}} 'cd rocc-pipelines && ./export-yolov5-annotations.sh ${{secrets.DB_SERVER}} ${{secrets.DB_NAME}} ${{secrets.DB_USERNAME}} ${{secrets.DB_PASSWORD}}'
      - name: Reset git changes
        run: ssh -p ${{secrets.SSH_PORT}} ${{secrets.USERNAME}}@${{secrets.HOST}} 'cd rocc-pipelines && git checkout -- .'
